elasticsearch:
    image: jlehikoinen/elasticsearch
    volumes:
        - elasticsearch:/data
    ports:
        - "9200:9200"
        - "9300:9300"
logstash:
    image: jlehikoinen/logstash
    links:
        - elasticsearch:elasticsearch
    ports:
        - "5000:5000"
        - "5000:5000/udp"
    command: -f /etc/logstash.conf
